---
# author: lework

# software_files_path: "/opt/software"

# cdh5_version: "6.2.0"
#cdh5_rpms_url: "http://archive.cloudera.com/cm5/redhat/6/x86_64/cm/{{ cdh5_version }}/RPMS/x86_64"
cdh5_rpms_url: "{{ cdh6_cloudera_repos }}/cloudera-repos/cm6/{{ cdh5_version }}/redhat7/yum/RPMS/x86_64"
#cdh5_jdk: "oracle-j2sdk1.8-1.8.0+update181-1.x86_64.rpm"
cdh5_file_path: "{{ software_files_path }}/{{ cdh5_jdk }}"
cdh5_jdk_url: "{{ cdh5_rpms_url }}/{{ cdh5_jdk }}"

#cdh5_java_home: "/usr/java/jdk1.8-1.8.0-cloudera"

#jdbc_version: "5.1.46"
jdbc_file: "mysql-connector-java-{{ jdbc_version }}.tar.gz"
jdbc_file_path: "{{ software_files_path }}/{{ jdbc_file }}"
jdbc_jar_file: "mysql-connector-java-{{ jdbc_version}}/mysql-connector-java-{{ jdbc_version }}-bin.jar"
#jdbc_file_url: "http://dev.mysql.com/get/Downloads/Connector-J/{{ jdbc_file }}"
jdbc_file_url: "{{ cdh6_mysql_repos }}/db-repos/mysql/{{ jdbc_file }}"


