---
# author: lework

# software_files_path: "/opt/software"

# cdh5_version: "5.11.0"
#cdh5_rpms_url: "http://archive.cloudera.com/cm5/redhat/{{ ansible_distribution_major_version }}/x86_64/cm/{{ cdh5_version }}/RPMS/x86_64"
cdh5_rpms_url: "{{ cdh6_cloudera_repos }}/cloudera-repos/cm6/{{ cdh5_version }}/redhat7/yum/RPMS/x86_64"

#cdh5_cm_daemons: "cloudera-manager-daemons-5.11.0-1.cm5110.p0.101.el{{ ansible_distribution_major_version }}.x86_64.rpm"
cdh5_cm_daemons_url: "{{ cdh5_rpms_url }}/{{ cdh5_cm_daemons }}"

#cdh5_cm_server: "cloudera-manager-server-5.11.0-1.cm5110.p0.101.el{{ ansible_distribution_major_version }}.x86_64.rpm"
cdh5_cm_server_url: "{{ cdh5_rpms_url }}/{{ cdh5_cm_server }}"

cdh5_cm_agent_url: "{{ cdh5_rpms_url }}/{{ cdh5_cm_agent }}"

#cdh5_parcels_url: "http://archive.cloudera.com/cdh5/parcels/{{ cdh5_version }}"
cdh5_parcels_url: "{{ cdh6_cloudera_repos }}/cloudera-repos/cdh6/{{ cdh5_version }}/parcels/"

#cdh5_parcels_cdh: "CDH-5.11.0-1.cdh5.11.0.p0.34-el{{ ansible_distribution_major_version }}.parcel"
cdh5_parcels_cdh_url: "{{ cdh5_parcels_url }}/{{ cdh5_parcels_cdh }}"

#cdh5_parcels_cdh_sha: "CDH-5.11.0-1.cdh5.11.0.p0.34-el{{ ansible_distribution_major_version }}.parcel.sha1"
cdh5_parcels_cdh_sha_url: "{{ cdh5_parcels_url }}/{{ cdh5_parcels_cdh_sha }}"

cdh5_parcels_manifest: "manifest.json"
cdh5_parcels_manifest_url: "{{ cdh5_parcels_url }}/{{ cdh5_parcels_manifest }}"

# jdbc_version: "5.1.40"
jdbc_file: "mysql-connector-java-{{ jdbc_version }}.tar.gz"
jdbc_file_path: "{{ software_files_path }}/{{ jdbc_file }}"
jdbc_jar_file: "mysql-connector-java-{{ jdbc_version}}/mysql-connector-java-{{ jdbc_version }}-bin.jar"
#jdbc_file_url: "http://101.96.10.44/dev.mysql.com/get/Downloads/Connector-J/{{ jdbc_file }}"
jdbc_file_url: "{{ cdh6_mysql_repos }}/db_repos/mysql/{{ jdbc_file }}"

cmf_db_host: "{{ mysql_host | default('localhost') }}"
cmf_db_port: "{{ mysql_port | default('3306') }}"
cmf_db_name: 'scm'
cmf_db_user: 'scm'
cmf_db_pass: '{{ mysql_password }}'

hive_db_name: 'metastore'
hive_db_user: 'hive'
hive_db_pass: '{{ mysql_password }}'

amon_db_name: 'amon'
amon_db_user: 'amon'
amon_db_pass: '{{ mysql_password }}'

rman_db_name: 'rman'
rman_db_user: 'rman'
rman_db_pass: '{{ mysql_password }}'

hue_db_name: 'hue'
hue_db_user: 'hue'
hue_db_pass: '{{ mysql_password }}'

oozie_db_name: 'oozie'
oozie_db_user: 'oozie'
oozie_db_pass: '{{ mysql_password }}'


sentry_db_name: 'sentry'
sentry_db_user: 'sentry'
sentry_db_pass: '{{ mysql_password }}'


nav_db_name: 'nav'
nav_db_user: 'nav'
nav_db_pass: '{{ mysql_password }}'


navms_db_name: 'navms'
navms_db_user: 'navms'
navms_db_pass: '{{ mysql_password }}'








